// Code generated by pigeon; DO NOT EDIT.

package count

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/raralabs/canal/network/builder/grammar/job/filter"
	"github.com/raralabs/canal/network/builder/utils"
	"github.com/raralabs/canal/transforms/event/poll"
)

var operatorMap = map[string]string{
	"||": "or",
	"&&": "and",
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Counter",
			pos:  position{line: 17, col: 1, offset: 305},
			expr: &actionExpr{
				pos: position{line: 17, col: 12, offset: 316},
				run: (*parser).callonCounter1,
				expr: &seqExpr{
					pos: position{line: 17, col: 12, offset: 316},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 17, col: 12, offset: 316},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 14, offset: 318},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 20, offset: 324},
								name: "CounterFactor",
							},
						},
						&labeledExpr{
							pos:   position{line: 17, col: 34, offset: 338},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 17, col: 39, offset: 343},
								expr: &seqExpr{
									pos: position{line: 17, col: 40, offset: 344},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 17, col: 40, offset: 344},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 17, col: 42, offset: 346},
											name: "Operators",
										},
										&ruleRefExpr{
											pos:  position{line: 17, col: 52, offset: 356},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 17, col: 54, offset: 358},
											name: "CounterFactor",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CounterFactor",
			pos:  position{line: 36, col: 1, offset: 904},
			expr: &choiceExpr{
				pos: position{line: 36, col: 18, offset: 921},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 36, col: 18, offset: 921},
						run: (*parser).callonCounterFactor2,
						expr: &seqExpr{
							pos: position{line: 36, col: 18, offset: 921},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 36, col: 18, offset: 921},
									val:        "(",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 36, col: 22, offset: 925},
									label: "cnt",
									expr: &ruleRefExpr{
										pos:  position{line: 36, col: 26, offset: 929},
										name: "Counter",
									},
								},
								&litMatcher{
									pos:        position{line: 36, col: 34, offset: 937},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 38, col: 5, offset: 973},
						run: (*parser).callonCounterFactor8,
						expr: &labeledExpr{
							pos:   position{line: 38, col: 5, offset: 973},
							label: "ce",
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 8, offset: 976},
								name: "CounterEvent",
							},
						},
					},
				},
			},
		},
		{
			name: "CounterEvent",
			pos:  position{line: 42, col: 1, offset: 1021},
			expr: &choiceExpr{
				pos: position{line: 42, col: 17, offset: 1037},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 42, col: 17, offset: 1037},
						name: "IntervalDesc",
					},
					&ruleRefExpr{
						pos:  position{line: 42, col: 32, offset: 1052},
						name: "MultiFilter",
					},
				},
			},
		},
		{
			name: "Operators",
			pos:  position{line: 44, col: 1, offset: 1067},
			expr: &choiceExpr{
				pos: position{line: 44, col: 14, offset: 1080},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 44, col: 14, offset: 1080},
						val:        "||",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 44, col: 21, offset: 1087},
						val:        "&&",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "IntervalDesc",
			pos:  position{line: 46, col: 1, offset: 1095},
			expr: &actionExpr{
				pos: position{line: 46, col: 17, offset: 1111},
				run: (*parser).callonIntervalDesc1,
				expr: &seqExpr{
					pos: position{line: 46, col: 17, offset: 1111},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 46, col: 17, offset: 1111},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 19, offset: 1113},
							val:        "interval",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 30, offset: 1124},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 32, offset: 1126},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 36, offset: 1130},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 38, offset: 1132},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 42, offset: 1136},
								name: "Number",
							},
						},
						&labeledExpr{
							pos:   position{line: 46, col: 49, offset: 1143},
							label: "unit",
							expr: &choiceExpr{
								pos: position{line: 46, col: 55, offset: 1149},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 46, col: 55, offset: 1149},
										val:        "s",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 46, col: 61, offset: 1155},
										val:        "m",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 46, col: 67, offset: 1161},
										val:        "h",
										ignoreCase: false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MultiFilter",
			pos:  position{line: 68, col: 1, offset: 1830},
			expr: &actionExpr{
				pos: position{line: 68, col: 16, offset: 1845},
				run: (*parser).callonMultiFilter1,
				expr: &seqExpr{
					pos: position{line: 68, col: 16, offset: 1845},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 68, col: 16, offset: 1845},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 22, offset: 1851},
								name: "FilterFactor",
							},
						},
						&labeledExpr{
							pos:   position{line: 68, col: 35, offset: 1864},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 68, col: 40, offset: 1869},
								expr: &seqExpr{
									pos: position{line: 68, col: 41, offset: 1870},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 68, col: 41, offset: 1870},
											name: "_",
										},
										&labeledExpr{
											pos:   position{line: 68, col: 43, offset: 1872},
											label: "op",
											expr: &ruleRefExpr{
												pos:  position{line: 68, col: 46, offset: 1875},
												name: "SecondaryFilterOperator",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 68, col: 70, offset: 1899},
											name: "_",
										},
										&labeledExpr{
											pos:   position{line: 68, col: 72, offset: 1901},
											label: "f2",
											expr: &ruleRefExpr{
												pos:  position{line: 68, col: 75, offset: 1904},
												name: "FilterFactor",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FilterFactor",
			pos:  position{line: 90, col: 1, offset: 2690},
			expr: &choiceExpr{
				pos: position{line: 90, col: 17, offset: 2706},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 90, col: 17, offset: 2706},
						run: (*parser).callonFilterFactor2,
						expr: &seqExpr{
							pos: position{line: 90, col: 17, offset: 2706},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 90, col: 17, offset: 2706},
									val:        "(",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 90, col: 21, offset: 2710},
									label: "sf",
									expr: &ruleRefExpr{
										pos:  position{line: 90, col: 24, offset: 2713},
										name: "MultiFilter",
									},
								},
								&litMatcher{
									pos:        position{line: 90, col: 36, offset: 2725},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 92, col: 5, offset: 2756},
						run: (*parser).callonFilterFactor8,
						expr: &labeledExpr{
							pos:   position{line: 92, col: 5, offset: 2756},
							label: "pf",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 8, offset: 2759},
								name: "PrimaryFilter",
							},
						},
					},
				},
			},
		},
		{
			name: "SecondaryFilterOperator",
			pos:  position{line: 96, col: 1, offset: 2801},
			expr: &choiceExpr{
				pos: position{line: 96, col: 28, offset: 2828},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 96, col: 28, offset: 2828},
						val:        "and",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 96, col: 36, offset: 2836},
						run: (*parser).callonSecondaryFilterOperator3,
						expr: &litMatcher{
							pos:        position{line: 96, col: 36, offset: 2836},
							val:        "or",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "PrimaryFilter",
			pos:  position{line: 103, col: 1, offset: 3015},
			expr: &actionExpr{
				pos: position{line: 103, col: 18, offset: 3032},
				run: (*parser).callonPrimaryFilter1,
				expr: &seqExpr{
					pos: position{line: 103, col: 18, offset: 3032},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 103, col: 18, offset: 3032},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 23, offset: 3037},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 103, col: 28, offset: 3042},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 103, col: 30, offset: 3044},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 33, offset: 3047},
								name: "PrimaryFilterOperator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 103, col: 55, offset: 3069},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 103, col: 57, offset: 3071},
							label: "value",
							expr: &choiceExpr{
								pos: position{line: 103, col: 64, offset: 3078},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 103, col: 64, offset: 3078},
										name: "val",
									},
									&ruleRefExpr{
										pos:  position{line: 103, col: 72, offset: 3086},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 103, col: 81, offset: 3095},
										name: "String_Type2",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PrimaryFilterOperator",
			pos:  position{line: 107, col: 1, offset: 3153},
			expr: &choiceExpr{
				pos: position{line: 107, col: 26, offset: 3178},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 107, col: 26, offset: 3178},
						val:        "==",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 107, col: 33, offset: 3185},
						val:        "!=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 107, col: 40, offset: 3192},
						val:        "<",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 107, col: 46, offset: 3198},
						val:        ">",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 107, col: 52, offset: 3204},
						val:        "<=",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 107, col: 59, offset: 3211},
						run: (*parser).callonPrimaryFilterOperator7,
						expr: &litMatcher{
							pos:        position{line: 107, col: 59, offset: 3211},
							val:        ">=",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 111, col: 1, offset: 3260},
			expr: &choiceExpr{
				pos: position{line: 111, col: 9, offset: 3268},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 111, col: 9, offset: 3268},
						run: (*parser).callonExpr2,
						expr: &seqExpr{
							pos: position{line: 111, col: 9, offset: 3268},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 111, col: 9, offset: 3268},
									name: "Variable",
								},
								&zeroOrMoreExpr{
									pos: position{line: 111, col: 18, offset: 3277},
									expr: &seqExpr{
										pos: position{line: 111, col: 20, offset: 3279},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 111, col: 20, offset: 3279},
												name: "_",
											},
											&choiceExpr{
												pos: position{line: 111, col: 23, offset: 3282},
												alternatives: []interface{}{
													&litMatcher{
														pos:        position{line: 111, col: 23, offset: 3282},
														val:        "%",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 111, col: 29, offset: 3288},
														val:        "-",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 111, col: 35, offset: 3294},
														val:        "+",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 111, col: 41, offset: 3300},
														val:        "*",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 111, col: 47, offset: 3306},
														val:        "/",
														ignoreCase: false,
													},
												},
											},
											&ruleRefExpr{
												pos:  position{line: 111, col: 52, offset: 3311},
												name: "_",
											},
											&choiceExpr{
												pos: position{line: 111, col: 55, offset: 3314},
												alternatives: []interface{}{
													&ruleRefExpr{
														pos:  position{line: 111, col: 55, offset: 3314},
														name: "Variable",
													},
													&ruleRefExpr{
														pos:  position{line: 111, col: 66, offset: 3325},
														name: "Number",
													},
												},
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 113, col: 5, offset: 3378},
						run: (*parser).callonExpr18,
						expr: &seqExpr{
							pos: position{line: 113, col: 5, offset: 3378},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 113, col: 5, offset: 3378},
									val:        "'",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 113, col: 9, offset: 3382},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 113, col: 14, offset: 3387},
										name: "Expr",
									},
								},
								&litMatcher{
									pos:        position{line: 113, col: 19, offset: 3392},
									val:        "'",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "val",
			pos:  position{line: 117, col: 1, offset: 3430},
			expr: &actionExpr{
				pos: position{line: 117, col: 10, offset: 3439},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 117, col: 10, offset: 3439},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 117, col: 15, offset: 3444},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 117, col: 15, offset: 3444},
								name: "Number",
							},
							&ruleRefExpr{
								pos:  position{line: 117, col: 24, offset: 3453},
								name: "Word",
							},
						},
					},
				},
			},
		},
		{
			name: "Variable",
			pos:  position{line: 121, col: 1, offset: 3492},
			expr: &actionExpr{
				pos: position{line: 121, col: 13, offset: 3504},
				run: (*parser).callonVariable1,
				expr: &seqExpr{
					pos: position{line: 121, col: 13, offset: 3504},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 121, col: 13, offset: 3504},
							name: "Letter",
						},
						&zeroOrMoreExpr{
							pos: position{line: 121, col: 20, offset: 3511},
							expr: &choiceExpr{
								pos: position{line: 121, col: 21, offset: 3512},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 121, col: 21, offset: 3512},
										name: "Integer",
									},
									&ruleRefExpr{
										pos:  position{line: 121, col: 31, offset: 3522},
										name: "Letter",
									},
									&litMatcher{
										pos:        position{line: 121, col: 39, offset: 3530},
										val:        "_",
										ignoreCase: false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "String_Type2",
			pos:  position{line: 125, col: 1, offset: 3580},
			expr: &actionExpr{
				pos: position{line: 125, col: 17, offset: 3596},
				run: (*parser).callonString_Type21,
				expr: &seqExpr{
					pos: position{line: 125, col: 17, offset: 3596},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 125, col: 17, offset: 3596},
							val:        "'",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 125, col: 21, offset: 3600},
							label: "w1",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 24, offset: 3603},
								name: "Word",
							},
						},
						&labeledExpr{
							pos:   position{line: 125, col: 29, offset: 3608},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 125, col: 34, offset: 3613},
								expr: &seqExpr{
									pos: position{line: 125, col: 36, offset: 3615},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 125, col: 36, offset: 3615},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 125, col: 38, offset: 3617},
											name: "Word",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 125, col: 46, offset: 3625},
							val:        "'",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 148, col: 1, offset: 4315},
			expr: &actionExpr{
				pos: position{line: 148, col: 11, offset: 4325},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 148, col: 11, offset: 4325},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 148, col: 11, offset: 4325},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 148, col: 15, offset: 4329},
							expr: &choiceExpr{
								pos: position{line: 148, col: 17, offset: 4331},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 148, col: 17, offset: 4331},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 148, col: 17, offset: 4331},
												expr: &ruleRefExpr{
													pos:  position{line: 148, col: 18, offset: 4332},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 148, col: 30, offset: 4344,
											},
										},
									},
									&seqExpr{
										pos: position{line: 148, col: 34, offset: 4348},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 148, col: 34, offset: 4348},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 148, col: 39, offset: 4353},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 148, col: 57, offset: 4371},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 155, col: 1, offset: 4553},
			expr: &charClassMatcher{
				pos:        position{line: 155, col: 16, offset: 4568},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 157, col: 1, offset: 4586},
			expr: &ruleRefExpr{
				pos:  position{line: 157, col: 19, offset: 4604},
				name: "SingleCharEscape",
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 159, col: 1, offset: 4624},
			expr: &charClassMatcher{
				pos:        position{line: 159, col: 21, offset: 4644},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Word",
			pos:  position{line: 161, col: 1, offset: 4659},
			expr: &actionExpr{
				pos: position{line: 161, col: 9, offset: 4667},
				run: (*parser).callonWord1,
				expr: &oneOrMoreExpr{
					pos: position{line: 161, col: 9, offset: 4667},
					expr: &choiceExpr{
						pos: position{line: 161, col: 10, offset: 4668},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 161, col: 10, offset: 4668},
								name: "Letter",
							},
							&litMatcher{
								pos:        position{line: 161, col: 19, offset: 4677},
								val:        "_",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "Letter",
			pos:  position{line: 165, col: 1, offset: 4727},
			expr: &choiceExpr{
				pos: position{line: 165, col: 11, offset: 4737},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 165, col: 11, offset: 4737},
						val:        "[a-z]",
						ranges:     []rune{'a', 'z'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 165, col: 19, offset: 4745},
						val:        "[A-Z]",
						ranges:     []rune{'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 167, col: 1, offset: 4754},
			expr: &actionExpr{
				pos: position{line: 167, col: 11, offset: 4764},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 167, col: 11, offset: 4764},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 167, col: 11, offset: 4764},
							expr: &litMatcher{
								pos:        position{line: 167, col: 11, offset: 4764},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 167, col: 16, offset: 4769},
							name: "Integer",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 171, col: 1, offset: 4842},
			expr: &choiceExpr{
				pos: position{line: 171, col: 12, offset: 4853},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 171, col: 12, offset: 4853},
						val:        "0",
						ignoreCase: false,
					},
					&seqExpr{
						pos: position{line: 171, col: 18, offset: 4859},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 171, col: 18, offset: 4859},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 171, col: 38, offset: 4879},
								expr: &ruleRefExpr{
									pos:  position{line: 171, col: 38, offset: 4879},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 173, col: 1, offset: 4896},
			expr: &charClassMatcher{
				pos:        position{line: 173, col: 17, offset: 4912},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 175, col: 1, offset: 4921},
			expr: &charClassMatcher{
				pos:        position{line: 175, col: 24, offset: 4944},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 177, col: 1, offset: 4953},
			expr: &zeroOrMoreExpr{
				pos: position{line: 177, col: 19, offset: 4971},
				expr: &charClassMatcher{
					pos:        position{line: 177, col: 19, offset: 4971},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "OneWhiteSpace",
			pos:  position{line: 179, col: 1, offset: 4985},
			expr: &charClassMatcher{
				pos:        position{line: 179, col: 18, offset: 5002},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 181, col: 1, offset: 5015},
			expr: &notExpr{
				pos: position{line: 181, col: 8, offset: 5022},
				expr: &anyMatcher{
					line: 181, col: 9, offset: 5023,
				},
			},
		},
	},
}

func (c *current) onCounter1(first, rest interface{}) (interface{}, error) {

	event := first.(poll.Event)

	restSl := utils.ToIfaceSlice(rest)

	for _, v := range restSl {
		restExpr := utils.ToIfaceSlice(v)
		r := restExpr[3].(poll.Event)
		op := restExpr[1]
		if operator, ok := utils.TryString(op); ok {
			lastEvent := event
			event = poll.NewCompositeEvent(operatorMap[operator], r, lastEvent)
		}
	}

	return event, nil
}

func (p *parser) callonCounter1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCounter1(stack["first"], stack["rest"])
}

func (c *current) onCounterFactor2(cnt interface{}) (interface{}, error) {

	return cnt, nil
}

func (p *parser) callonCounterFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCounterFactor2(stack["cnt"])
}

func (c *current) onCounterFactor8(ce interface{}) (interface{}, error) {

	return ce, nil
}

func (p *parser) callonCounterFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCounterFactor8(stack["ce"])
}

func (c *current) onIntervalDesc1(val, unit interface{}) (interface{}, error) {

	v := val.(int64)
	u, _ := utils.TryString(unit)

	var interval time.Duration

	switch u {
	case "s":
		interval = time.Duration(v) * time.Second
	case "m":
		interval = time.Duration(60*v) * time.Second
	case "h":
		interval = time.Duration(60*60*v) * time.Second
	default:
		return nil, errors.New("Non-supported time unit.")
	}

	return poll.NewTimerEvent(interval), nil
}

func (p *parser) callonIntervalDesc1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntervalDesc1(stack["val"], stack["unit"])
}

func (c *current) onMultiFilter1(first, rest interface{}) (interface{}, error) {

	if filterDesc, ok := utils.TryString(string(c.text)); ok {

		filt, err := filter.Parse("", []byte(filterDesc))
		if err != nil {
			log.Fatalf("Could not parse filter: %v\n", err)
		}

		if f, ok := filt.(filter.Filter); ok {
			eventFilter := func(m map[string]interface{}) bool {
				out, _ := f(m)
				return out
			}
			return poll.NewFilterEvent(eventFilter), nil
		}
	}

	return nil, errors.New("Could not parse filter!!")
}

func (p *parser) callonMultiFilter1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiFilter1(stack["first"], stack["rest"])
}

func (c *current) onFilterFactor2(sf interface{}) (interface{}, error) {

	return sf, nil
}

func (p *parser) callonFilterFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterFactor2(stack["sf"])
}

func (c *current) onFilterFactor8(pf interface{}) (interface{}, error) {

	return pf, nil
}

func (p *parser) callonFilterFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterFactor8(stack["pf"])
}

func (c *current) onSecondaryFilterOperator3() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonSecondaryFilterOperator3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSecondaryFilterOperator3()
}

func (c *current) onPrimaryFilter1(name, op, value interface{}) (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonPrimaryFilter1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrimaryFilter1(stack["name"], stack["op"], stack["value"])
}

func (c *current) onPrimaryFilterOperator7() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonPrimaryFilterOperator7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrimaryFilterOperator7()
}

func (c *current) onExpr2() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonExpr2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr2()
}

func (c *current) onExpr18(expr interface{}) (interface{}, error) {

	return expr, nil
}

func (p *parser) callonExpr18() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr18(stack["expr"])
}

func (c *current) onValue1(val interface{}) (interface{}, error) {

	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onVariable1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonVariable1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable1()
}

func (c *current) onString_Type21(w1, rest interface{}) (interface{}, error) {

	var str strings.Builder

	if w, ok := w1.(string); ok {

		str.WriteString(w)
		rst := utils.ToIfaceSlice(rest)

		for _, v := range rst {
			rstStr := utils.ToIfaceSlice(v)
			if len(rstStr) == 2 {
				if wrd, ok := rstStr[1].(string); ok {
					str.WriteString(" ")
					str.WriteString(wrd)
				}
			}
		}
	}
	s := str.String()

	return utils.GetStringValue(s), nil
}

func (p *parser) callonString_Type21() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString_Type21(stack["w1"], stack["rest"])
}

func (c *current) onString1() (interface{}, error) {

	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	str, _ := strconv.Unquote(string(c.text))

	return utils.GetStringValue(str), nil
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onWord1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1()
}

func (c *current) onNumber1() (interface{}, error) {

	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
