// Code generated by pigeon; DO NOT EDIT.

package node

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/n-is/canal/network/builder/grammar/job/filter"
	"github.com/n-is/canal/network/builder/utils"
	"github.com/n-is/canal/transforms/event/poll"
)

type Instruction struct {
	Type   utils.JobType // ValueType of the job
	Name   string        // Name of the job
	Desc   string        // Description of the job
	Group  []string
	Params poll.Event
}

type Creation struct {
	Incomings []interface{}
}

var jobMap = map[string]utils.JobType{
	"filter": utils.FILTER,
	"branch": utils.BRANCH,
	"lua":    utils.LUA,
	"count":  utils.COUNT,
	"pass":   utils.PASS,

	"stdout":    utils.STDOUT,
	"blackhole": utils.BLACKHOLE,
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Node",
			pos:  position{line: 34, col: 1, offset: 734},
			expr: &choiceExpr{
				pos: position{line: 34, col: 9, offset: 742},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 34, col: 9, offset: 742},
						run: (*parser).callonNode2,
						expr: &seqExpr{
							pos: position{line: 34, col: 9, offset: 742},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 34, col: 9, offset: 742},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 34, col: 11, offset: 744},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 34, col: 16, offset: 749},
										name: "Variable",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 34, col: 25, offset: 758},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 34, col: 27, offset: 760},
									val:        "@",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 34, col: 31, offset: 764},
									label: "job",
									expr: &ruleRefExpr{
										pos:  position{line: 34, col: 35, offset: 768},
										name: "JobType",
									},
								},
								&labeledExpr{
									pos:   position{line: 34, col: 43, offset: 776},
									label: "param",
									expr: &ruleRefExpr{
										pos:  position{line: 34, col: 49, offset: 782},
										name: "InitialParam",
									},
								},
								&labeledExpr{
									pos:   position{line: 34, col: 62, offset: 795},
									label: "group",
									expr: &zeroOrOneExpr{
										pos: position{line: 34, col: 68, offset: 801},
										expr: &ruleRefExpr{
											pos:  position{line: 34, col: 69, offset: 802},
											name: "GroupBy",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 34, col: 79, offset: 812},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 34, col: 81, offset: 814},
									label: "desc",
									expr: &zeroOrOneExpr{
										pos: position{line: 34, col: 86, offset: 819},
										expr: &ruleRefExpr{
											pos:  position{line: 34, col: 86, offset: 819},
											name: "JobDescription",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 70, col: 1, offset: 1944},
						run: (*parser).callonNode20,
						expr: &seqExpr{
							pos: position{line: 70, col: 1, offset: 1944},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 70, col: 1, offset: 1944},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 70, col: 3, offset: 1946},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 70, col: 8, offset: 1951},
										name: "Variable",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 17, offset: 1960},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 70, col: 19, offset: 1962},
									val:        "@",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 23, offset: 1966},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 70, col: 25, offset: 1968},
									val:        "from:",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 70, col: 33, offset: 1976},
									label: "incomings",
									expr: &oneOrMoreExpr{
										pos: position{line: 70, col: 43, offset: 1986},
										expr: &ruleRefExpr{
											pos:  position{line: 70, col: 44, offset: 1987},
											name: "NodeJob",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "InitialParam",
			pos:  position{line: 74, col: 1, offset: 2098},
			expr: &actionExpr{
				pos: position{line: 74, col: 17, offset: 2114},
				run: (*parser).callonInitialParam1,
				expr: &seqExpr{
					pos: position{line: 74, col: 17, offset: 2114},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 74, col: 17, offset: 2114},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 74, col: 21, offset: 2118},
							label: "filt",
							expr: &zeroOrOneExpr{
								pos: position{line: 74, col: 26, offset: 2123},
								expr: &ruleRefExpr{
									pos:  position{line: 74, col: 26, offset: 2123},
									name: "MultiFilter",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 74, col: 39, offset: 2136},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "GroupBy",
			pos:  position{line: 78, col: 1, offset: 2174},
			expr: &actionExpr{
				pos: position{line: 78, col: 12, offset: 2185},
				run: (*parser).callonGroupBy1,
				expr: &seqExpr{
					pos: position{line: 78, col: 12, offset: 2185},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 78, col: 12, offset: 2185},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 78, col: 14, offset: 2187},
							val:        "by ",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 20, offset: 2193},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 78, col: 22, offset: 2195},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 78, col: 28, offset: 2201},
								name: "Variable",
							},
						},
						&labeledExpr{
							pos:   position{line: 78, col: 37, offset: 2210},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 78, col: 42, offset: 2215},
								expr: &seqExpr{
									pos: position{line: 78, col: 43, offset: 2216},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 78, col: 43, offset: 2216},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 78, col: 47, offset: 2220},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 78, col: 49, offset: 2222},
											name: "Variable",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 60, offset: 2233},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "NodeJob",
			pos:  position{line: 91, col: 1, offset: 2525},
			expr: &actionExpr{
				pos: position{line: 91, col: 12, offset: 2536},
				run: (*parser).callonNodeJob1,
				expr: &seqExpr{
					pos: position{line: 91, col: 12, offset: 2536},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 91, col: 12, offset: 2536},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 91, col: 14, offset: 2538},
							label: "nodeName",
							expr: &ruleRefExpr{
								pos:  position{line: 91, col: 23, offset: 2547},
								name: "Variable",
							},
						},
						&litMatcher{
							pos:        position{line: 91, col: 32, offset: 2556},
							val:        ".",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 91, col: 36, offset: 2560},
							label: "jobName",
							expr: &ruleRefExpr{
								pos:  position{line: 91, col: 44, offset: 2568},
								name: "Variable",
							},
						},
					},
				},
			},
		},
		{
			name: "JobType",
			pos:  position{line: 95, col: 1, offset: 2639},
			expr: &actionExpr{
				pos: position{line: 95, col: 12, offset: 2650},
				run: (*parser).callonJobType1,
				expr: &labeledExpr{
					pos:   position{line: 95, col: 12, offset: 2650},
					label: "jobType",
					expr: &choiceExpr{
						pos: position{line: 95, col: 21, offset: 2659},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 95, col: 21, offset: 2659},
								name: "executorType",
							},
							&ruleRefExpr{
								pos:  position{line: 95, col: 37, offset: 2675},
								name: "SinkType",
							},
						},
					},
				},
			},
		},
		{
			name: "executorType",
			pos:  position{line: 105, col: 1, offset: 2924},
			expr: &choiceExpr{
				pos: position{line: 105, col: 18, offset: 2941},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 105, col: 18, offset: 2941},
						val:        "filter",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 105, col: 29, offset: 2952},
						val:        "branch",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 105, col: 40, offset: 2963},
						val:        "lua",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 105, col: 48, offset: 2971},
						val:        "count",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 105, col: 58, offset: 2981},
						run: (*parser).callonProcessorType6,
						expr: &litMatcher{
							pos:        position{line: 105, col: 58, offset: 2981},
							val:        "pass",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "SinkType",
			pos:  position{line: 109, col: 1, offset: 3032},
			expr: &choiceExpr{
				pos: position{line: 109, col: 13, offset: 3044},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 109, col: 13, offset: 3044},
						val:        "stdout",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 109, col: 24, offset: 3055},
						run: (*parser).callonSinkType3,
						expr: &litMatcher{
							pos:        position{line: 109, col: 24, offset: 3055},
							val:        "blackhole",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "JobDescription",
			pos:  position{line: 113, col: 1, offset: 3111},
			expr: &actionExpr{
				pos: position{line: 113, col: 19, offset: 3129},
				run: (*parser).callonJobDescription1,
				expr: &seqExpr{
					pos: position{line: 113, col: 19, offset: 3129},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 113, col: 19, offset: 3129},
							label: "iden",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 24, offset: 3134},
								name: "Variable",
							},
						},
						&labeledExpr{
							pos:   position{line: 113, col: 33, offset: 3143},
							label: "param",
							expr: &zeroOrOneExpr{
								pos: position{line: 113, col: 39, offset: 3149},
								expr: &ruleRefExpr{
									pos:  position{line: 113, col: 39, offset: 3149},
									name: "JobParameters",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "JobParameters",
			pos:  position{line: 118, col: 1, offset: 3252},
			expr: &actionExpr{
				pos: position{line: 118, col: 18, offset: 3269},
				run: (*parser).callonJobParameters1,
				expr: &seqExpr{
					pos: position{line: 118, col: 18, offset: 3269},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 118, col: 18, offset: 3269},
							val:        ":",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 22, offset: 3273},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 118, col: 24, offset: 3275},
							label: "params",
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 31, offset: 3282},
								name: "AnySequence",
							},
						},
					},
				},
			},
		},
		{
			name: "MultiFilter",
			pos:  position{line: 124, col: 1, offset: 3463},
			expr: &actionExpr{
				pos: position{line: 124, col: 16, offset: 3478},
				run: (*parser).callonMultiFilter1,
				expr: &seqExpr{
					pos: position{line: 124, col: 16, offset: 3478},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 124, col: 16, offset: 3478},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 124, col: 22, offset: 3484},
								name: "FilterFactor",
							},
						},
						&labeledExpr{
							pos:   position{line: 124, col: 35, offset: 3497},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 124, col: 40, offset: 3502},
								expr: &seqExpr{
									pos: position{line: 124, col: 41, offset: 3503},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 124, col: 41, offset: 3503},
											name: "_",
										},
										&labeledExpr{
											pos:   position{line: 124, col: 43, offset: 3505},
											label: "op",
											expr: &ruleRefExpr{
												pos:  position{line: 124, col: 46, offset: 3508},
												name: "SecondaryFilterOperator",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 124, col: 70, offset: 3532},
											name: "_",
										},
										&labeledExpr{
											pos:   position{line: 124, col: 72, offset: 3534},
											label: "f2",
											expr: &ruleRefExpr{
												pos:  position{line: 124, col: 75, offset: 3537},
												name: "FilterFactor",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FilterFactor",
			pos:  position{line: 146, col: 1, offset: 4323},
			expr: &choiceExpr{
				pos: position{line: 146, col: 17, offset: 4339},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 146, col: 17, offset: 4339},
						run: (*parser).callonFilterFactor2,
						expr: &seqExpr{
							pos: position{line: 146, col: 17, offset: 4339},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 146, col: 17, offset: 4339},
									val:        "(",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 146, col: 21, offset: 4343},
									label: "sf",
									expr: &ruleRefExpr{
										pos:  position{line: 146, col: 24, offset: 4346},
										name: "MultiFilter",
									},
								},
								&litMatcher{
									pos:        position{line: 146, col: 36, offset: 4358},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 148, col: 5, offset: 4389},
						run: (*parser).callonFilterFactor8,
						expr: &labeledExpr{
							pos:   position{line: 148, col: 5, offset: 4389},
							label: "pf",
							expr: &ruleRefExpr{
								pos:  position{line: 148, col: 8, offset: 4392},
								name: "PrimaryFilter",
							},
						},
					},
				},
			},
		},
		{
			name: "SecondaryFilterOperator",
			pos:  position{line: 152, col: 1, offset: 4434},
			expr: &choiceExpr{
				pos: position{line: 152, col: 28, offset: 4461},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 152, col: 28, offset: 4461},
						val:        "and",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 152, col: 36, offset: 4469},
						run: (*parser).callonSecondaryFilterOperator3,
						expr: &litMatcher{
							pos:        position{line: 152, col: 36, offset: 4469},
							val:        "or",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "PrimaryFilter",
			pos:  position{line: 159, col: 1, offset: 4648},
			expr: &actionExpr{
				pos: position{line: 159, col: 18, offset: 4665},
				run: (*parser).callonPrimaryFilter1,
				expr: &seqExpr{
					pos: position{line: 159, col: 18, offset: 4665},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 159, col: 18, offset: 4665},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 23, offset: 4670},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 28, offset: 4675},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 159, col: 30, offset: 4677},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 33, offset: 4680},
								name: "PrimaryFilterOperator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 55, offset: 4702},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 159, col: 57, offset: 4704},
							label: "value",
							expr: &choiceExpr{
								pos: position{line: 159, col: 64, offset: 4711},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 159, col: 64, offset: 4711},
										name: "val",
									},
									&ruleRefExpr{
										pos:  position{line: 159, col: 72, offset: 4719},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 159, col: 81, offset: 4728},
										name: "String_Type2",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PrimaryFilterOperator",
			pos:  position{line: 163, col: 1, offset: 4786},
			expr: &choiceExpr{
				pos: position{line: 163, col: 26, offset: 4811},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 163, col: 26, offset: 4811},
						val:        "==",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 163, col: 33, offset: 4818},
						val:        "!=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 163, col: 40, offset: 4825},
						val:        "<",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 163, col: 46, offset: 4831},
						val:        ">",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 163, col: 52, offset: 4837},
						val:        "<=",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 163, col: 59, offset: 4844},
						run: (*parser).callonPrimaryFilterOperator7,
						expr: &litMatcher{
							pos:        position{line: 163, col: 59, offset: 4844},
							val:        ">=",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 167, col: 1, offset: 4893},
			expr: &choiceExpr{
				pos: position{line: 167, col: 9, offset: 4901},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 167, col: 9, offset: 4901},
						run: (*parser).callonExpr2,
						expr: &seqExpr{
							pos: position{line: 167, col: 9, offset: 4901},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 167, col: 9, offset: 4901},
									name: "Variable",
								},
								&zeroOrMoreExpr{
									pos: position{line: 167, col: 18, offset: 4910},
									expr: &seqExpr{
										pos: position{line: 167, col: 20, offset: 4912},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 167, col: 20, offset: 4912},
												name: "_",
											},
											&choiceExpr{
												pos: position{line: 167, col: 23, offset: 4915},
												alternatives: []interface{}{
													&litMatcher{
														pos:        position{line: 167, col: 23, offset: 4915},
														val:        "%",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 167, col: 29, offset: 4921},
														val:        "-",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 167, col: 35, offset: 4927},
														val:        "+",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 167, col: 41, offset: 4933},
														val:        "*",
														ignoreCase: false,
													},
													&litMatcher{
														pos:        position{line: 167, col: 47, offset: 4939},
														val:        "/",
														ignoreCase: false,
													},
												},
											},
											&ruleRefExpr{
												pos:  position{line: 167, col: 52, offset: 4944},
												name: "_",
											},
											&choiceExpr{
												pos: position{line: 167, col: 55, offset: 4947},
												alternatives: []interface{}{
													&ruleRefExpr{
														pos:  position{line: 167, col: 55, offset: 4947},
														name: "Variable",
													},
													&ruleRefExpr{
														pos:  position{line: 167, col: 66, offset: 4958},
														name: "Number",
													},
												},
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 169, col: 5, offset: 5011},
						run: (*parser).callonExpr18,
						expr: &seqExpr{
							pos: position{line: 169, col: 5, offset: 5011},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 169, col: 5, offset: 5011},
									val:        "'",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 169, col: 9, offset: 5015},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 169, col: 14, offset: 5020},
										name: "Expr",
									},
								},
								&litMatcher{
									pos:        position{line: 169, col: 19, offset: 5025},
									val:        "'",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "String_Type2",
			pos:  position{line: 173, col: 1, offset: 5063},
			expr: &actionExpr{
				pos: position{line: 173, col: 17, offset: 5079},
				run: (*parser).callonString_Type21,
				expr: &seqExpr{
					pos: position{line: 173, col: 17, offset: 5079},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 173, col: 17, offset: 5079},
							val:        "'",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 173, col: 21, offset: 5083},
							label: "w1",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 24, offset: 5086},
								name: "Word",
							},
						},
						&labeledExpr{
							pos:   position{line: 173, col: 29, offset: 5091},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 173, col: 34, offset: 5096},
								expr: &seqExpr{
									pos: position{line: 173, col: 36, offset: 5098},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 173, col: 36, offset: 5098},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 173, col: 38, offset: 5100},
											name: "Word",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 173, col: 46, offset: 5108},
							val:        "'",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 196, col: 1, offset: 5798},
			expr: &actionExpr{
				pos: position{line: 196, col: 11, offset: 5808},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 196, col: 11, offset: 5808},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 196, col: 11, offset: 5808},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 196, col: 15, offset: 5812},
							expr: &choiceExpr{
								pos: position{line: 196, col: 17, offset: 5814},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 196, col: 17, offset: 5814},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 196, col: 17, offset: 5814},
												expr: &ruleRefExpr{
													pos:  position{line: 196, col: 18, offset: 5815},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 196, col: 30, offset: 5827,
											},
										},
									},
									&seqExpr{
										pos: position{line: 196, col: 34, offset: 5831},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 196, col: 34, offset: 5831},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 196, col: 39, offset: 5836},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 196, col: 57, offset: 5854},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "val",
			pos:  position{line: 203, col: 1, offset: 6036},
			expr: &actionExpr{
				pos: position{line: 203, col: 10, offset: 6045},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 203, col: 10, offset: 6045},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 203, col: 15, offset: 6050},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 203, col: 15, offset: 6050},
								name: "Number",
							},
							&ruleRefExpr{
								pos:  position{line: 203, col: 24, offset: 6059},
								name: "Word",
							},
						},
					},
				},
			},
		},
		{
			name: "Variable",
			pos:  position{line: 207, col: 1, offset: 6098},
			expr: &actionExpr{
				pos: position{line: 207, col: 13, offset: 6110},
				run: (*parser).callonVariable1,
				expr: &seqExpr{
					pos: position{line: 207, col: 13, offset: 6110},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 207, col: 13, offset: 6110},
							name: "Letter",
						},
						&zeroOrMoreExpr{
							pos: position{line: 207, col: 20, offset: 6117},
							expr: &choiceExpr{
								pos: position{line: 207, col: 21, offset: 6118},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 207, col: 21, offset: 6118},
										name: "Integer",
									},
									&ruleRefExpr{
										pos:  position{line: 207, col: 31, offset: 6128},
										name: "Letter",
									},
									&litMatcher{
										pos:        position{line: 207, col: 39, offset: 6136},
										val:        "_",
										ignoreCase: false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AnySequence",
			pos:  position{line: 211, col: 1, offset: 6186},
			expr: &actionExpr{
				pos: position{line: 211, col: 16, offset: 6201},
				run: (*parser).callonAnySequence1,
				expr: &oneOrMoreExpr{
					pos: position{line: 211, col: 16, offset: 6201},
					expr: &choiceExpr{
						pos: position{line: 211, col: 17, offset: 6202},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 211, col: 17, offset: 6202},
								name: "Symbol",
							},
							&ruleRefExpr{
								pos:  position{line: 211, col: 26, offset: 6211},
								name: "Letter",
							},
							&ruleRefExpr{
								pos:  position{line: 211, col: 35, offset: 6220},
								name: "DecimalDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 211, col: 50, offset: 6235},
								name: "OneWhiteSpace",
							},
						},
					},
				},
			},
		},
		{
			name: "Symbol",
			pos:  position{line: 215, col: 1, offset: 6295},
			expr: &choiceExpr{
				pos: position{line: 215, col: 12, offset: 6306},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 215, col: 12, offset: 6306},
						val:        "|",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 18, offset: 6312},
						val:        " ",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 24, offset: 6318},
						val:        "!",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 30, offset: 6324},
						val:        "#",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 36, offset: 6330},
						val:        "$",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 42, offset: 6336},
						val:        "%",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 48, offset: 6342},
						val:        "&",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 54, offset: 6348},
						val:        "(",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 60, offset: 6354},
						val:        ")",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 66, offset: 6360},
						val:        "*",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 215, col: 72, offset: 6366},
						val:        "+",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 9, offset: 6381},
						val:        ",",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 15, offset: 6387},
						val:        "-",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 21, offset: 6393},
						val:        ".",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 27, offset: 6399},
						val:        "/",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 33, offset: 6405},
						val:        ":",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 39, offset: 6411},
						val:        ";",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 45, offset: 6417},
						val:        ">",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 51, offset: 6423},
						val:        "=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 57, offset: 6429},
						val:        "<",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 63, offset: 6435},
						val:        "?",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 69, offset: 6441},
						val:        "@",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 216, col: 75, offset: 6447},
						val:        "[",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 9, offset: 6462},
						val:        "\\",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 16, offset: 6469},
						val:        "]",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 22, offset: 6475},
						val:        "^",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 28, offset: 6481},
						val:        "_",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 34, offset: 6487},
						val:        "`",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 40, offset: 6493},
						val:        "{",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 46, offset: 6499},
						val:        "}",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 52, offset: 6505},
						val:        "~",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 58, offset: 6511},
						val:        "'",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "Word",
			pos:  position{line: 220, col: 1, offset: 6520},
			expr: &actionExpr{
				pos: position{line: 220, col: 9, offset: 6528},
				run: (*parser).callonWord1,
				expr: &oneOrMoreExpr{
					pos: position{line: 220, col: 9, offset: 6528},
					expr: &choiceExpr{
						pos: position{line: 220, col: 10, offset: 6529},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 220, col: 10, offset: 6529},
								name: "Letter",
							},
							&litMatcher{
								pos:        position{line: 220, col: 19, offset: 6538},
								val:        "_",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "Letter",
			pos:  position{line: 224, col: 1, offset: 6588},
			expr: &choiceExpr{
				pos: position{line: 224, col: 11, offset: 6598},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 224, col: 11, offset: 6598},
						val:        "[a-z]",
						ranges:     []rune{'a', 'z'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 224, col: 19, offset: 6606},
						val:        "[A-Z]",
						ranges:     []rune{'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 226, col: 1, offset: 6615},
			expr: &actionExpr{
				pos: position{line: 226, col: 11, offset: 6625},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 226, col: 11, offset: 6625},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 226, col: 11, offset: 6625},
							expr: &litMatcher{
								pos:        position{line: 226, col: 11, offset: 6625},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 226, col: 16, offset: 6630},
							name: "Integer",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 230, col: 1, offset: 6703},
			expr: &choiceExpr{
				pos: position{line: 230, col: 12, offset: 6714},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 230, col: 12, offset: 6714},
						val:        "0",
						ignoreCase: false,
					},
					&seqExpr{
						pos: position{line: 230, col: 18, offset: 6720},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 230, col: 18, offset: 6720},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 230, col: 38, offset: 6740},
								expr: &ruleRefExpr{
									pos:  position{line: 230, col: 38, offset: 6740},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 232, col: 1, offset: 6757},
			expr: &charClassMatcher{
				pos:        position{line: 232, col: 17, offset: 6773},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 234, col: 1, offset: 6782},
			expr: &charClassMatcher{
				pos:        position{line: 234, col: 24, offset: 6805},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 236, col: 1, offset: 6814},
			expr: &zeroOrMoreExpr{
				pos: position{line: 236, col: 19, offset: 6832},
				expr: &charClassMatcher{
					pos:        position{line: 236, col: 19, offset: 6832},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "OneWhiteSpace",
			pos:  position{line: 238, col: 1, offset: 6846},
			expr: &charClassMatcher{
				pos:        position{line: 238, col: 18, offset: 6863},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 240, col: 1, offset: 6876},
			expr: &notExpr{
				pos: position{line: 240, col: 8, offset: 6883},
				expr: &anyMatcher{
					line: 240, col: 9, offset: 6884,
				},
			},
		},
	},
}

func (c *current) onNode2(name, job, param, group, desc interface{}) (interface{}, error) {

	nodeName := name

	jobType, ok := job.(utils.JobType)
	if !ok {
		log.Fatalln("The requested job is not yet implemented")
	}

	var filt poll.Event
	if param != nil {
		filt, ok = param.(poll.Event)
		if !ok {
			log.Fatalln("The requested parameter is not supported")
		}
	}

	jobName := ""
	jobParams := ""
	if desc != nil {
		d := utils.ToIfaceSlice(desc)
		jobName, _ = d[0].(string)
		jobParams, _ = d[1].(string)
	}

	var groupBy []string
	if group != nil {
		for _, v := range utils.ToIfaceSlice(group) {
			if str, ok := utils.TryString(v); ok {
				groupBy = append(groupBy, str)
			}
		}
	}

	return []interface{}{nodeName, Instruction{Type: jobType, Name: jobName,
		Group: groupBy, Desc: jobParams, Params: filt}}, nil
}

func (p *parser) callonNode2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNode2(stack["name"], stack["job"], stack["param"], stack["group"], stack["desc"])
}

func (c *current) onNode20(name, incomings interface{}) (interface{}, error) {

	return []interface{}{name, Creation{Incomings: utils.ToIfaceSlice(incomings)}}, nil
}

func (p *parser) callonNode20() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNode20(stack["name"], stack["incomings"])
}

func (c *current) onInitialParam1(filt interface{}) (interface{}, error) {

	return filt, nil
}

func (p *parser) callonInitialParam1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInitialParam1(stack["filt"])
}

func (c *current) onGroupBy1(first, rest interface{}) (interface{}, error) {

	var group []interface{}
	group = append(group, first)

	restG := utils.ToIfaceSlice(rest)
	for _, v := range restG {
		gr := utils.ToIfaceSlice(v)
		group = append(group, gr[2])
	}

	return group, nil
}

func (p *parser) callonGroupBy1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupBy1(stack["first"], stack["rest"])
}

func (c *current) onNodeJob1(nodeName, jobName interface{}) (interface{}, error) {

	return []interface{}{nodeName, jobName}, nil
}

func (p *parser) callonNodeJob1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNodeJob1(stack["nodeName"], stack["jobName"])
}

func (c *current) onJobType1(jobType interface{}) (interface{}, error) {

	switch s := jobType.(type) {
	case []uint8:
		return jobMap[string(s)], nil
	case string:
		return jobMap[s], nil
	}
	return nil, errors.New("Unknown JobType")
}

func (p *parser) callonJobType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJobType1(stack["jobType"])
}

func (c *current) onProcessorType6() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonProcessorType6() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProcessorType6()
}

func (c *current) onSinkType3() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonSinkType3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSinkType3()
}

func (c *current) onJobDescription1(iden, param interface{}) (interface{}, error) {

	nameParam := []interface{}{iden, param}
	return nameParam, nil
}

func (p *parser) callonJobDescription1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJobDescription1(stack["iden"], stack["param"])
}

func (c *current) onJobParameters1(params interface{}) (interface{}, error) {

	return params, nil
}

func (p *parser) callonJobParameters1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJobParameters1(stack["params"])
}

func (c *current) onMultiFilter1(first, rest interface{}) (interface{}, error) {

	if filterDesc, ok := utils.TryString(string(c.text)); ok {

		filt, err := filter.Parse("", []byte(filterDesc))
		if err != nil {
			log.Fatalf("Could not parse filter: %v\n", err)
		}

		if f, ok := filt.(filter.Filter); ok {
			eventFilter := func(m map[string]interface{}) bool {
				out, _ := f(m)
				return out
			}
			return poll.NewFilterEvent(eventFilter), nil
		}
	}

	return nil, errors.New("Could not parse filter!!")
}

func (p *parser) callonMultiFilter1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiFilter1(stack["first"], stack["rest"])
}

func (c *current) onFilterFactor2(sf interface{}) (interface{}, error) {

	return sf, nil
}

func (p *parser) callonFilterFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterFactor2(stack["sf"])
}

func (c *current) onFilterFactor8(pf interface{}) (interface{}, error) {

	return pf, nil
}

func (p *parser) callonFilterFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterFactor8(stack["pf"])
}

func (c *current) onSecondaryFilterOperator3() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonSecondaryFilterOperator3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSecondaryFilterOperator3()
}

func (c *current) onPrimaryFilter1(name, op, value interface{}) (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonPrimaryFilter1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrimaryFilter1(stack["name"], stack["op"], stack["value"])
}

func (c *current) onPrimaryFilterOperator7() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonPrimaryFilterOperator7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrimaryFilterOperator7()
}

func (c *current) onExpr2() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonExpr2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr2()
}

func (c *current) onExpr18(expr interface{}) (interface{}, error) {

	return expr, nil
}

func (p *parser) callonExpr18() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr18(stack["expr"])
}

func (c *current) onString_Type21(w1, rest interface{}) (interface{}, error) {

	var str strings.Builder

	if w, ok := w1.(string); ok {

		str.WriteString(w)
		rst := utils.ToIfaceSlice(rest)

		for _, v := range rst {
			rstStr := utils.ToIfaceSlice(v)
			if len(rstStr) == 2 {
				if wrd, ok := rstStr[1].(string); ok {
					str.WriteString(" ")
					str.WriteString(wrd)
				}
			}
		}
	}
	s := str.String()

	return utils.GetStringValue(s), nil
}

func (p *parser) callonString_Type21() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString_Type21(stack["w1"], stack["rest"])
}

func (c *current) onString1() (interface{}, error) {

	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	str, _ := strconv.Unquote(string(c.text))

	return utils.GetStringValue(str), nil
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onValue1(val interface{}) (interface{}, error) {

	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onVariable1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonVariable1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable1()
}

func (c *current) onAnySequence1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonAnySequence1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnySequence1()
}

func (c *current) onWord1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1()
}

func (c *current) onNumber1() (interface{}, error) {

	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
